import { Media as MediaType } from '@/payload-types'
import { authenticated } from '@/shared/access/authenticated'
import { CollectionGroups } from '@/shared/CollectionGroups'
import { CollectionConfig } from 'payload'

export const Media: CollectionConfig = {
  slug: 'media',
  admin: {
    group: CollectionGroups.MediaCollections,
    defaultColumns: ['filename', 'title', 'alt', 'createdAt', 'updatedAt'],
  },
  upload: {
    mimeTypes: ['image/*', 'application/pdf'],
    imageSizes: [
      {
        name: 'xs',
        width: 480,
      },
      {
        name: 'sm',
        width: 768,
      },
      {
        name: 'md',
        width: 1024,
      },
      {
        name: 'lg',
        width: 1920,
      },
      {
        name: 'xl',
        width: 2560,
      },
      {
        // optimal size for an Open Graph (OG) image
        name: 'og',
        width: 1200,
        height: 630,
      },
    ],
    // Specifying a function as adminThumbnail is the only way to fall back to different sizes.
    adminThumbnail: ({ doc }) => {
      const media = doc as unknown as MediaType
      const filename =
        media.sizes?.sm?.filename ||
        media.sizes?.md?.filename ||
        media.sizes?.lg?.filename ||
        media.filename

      return filename ? generateFileURL({ filename }) : null
    },
  },
  access: {
    read: authenticated,
    update: authenticated,
    delete: authenticated,
    create: authenticated,
  },
  // the alt and keywords fields are generated by the payload-alt-text plugin
  fields: [],
}

/**
 * Generates the public URL for a media file, overriding the raw S3 URL stored in the database
 * with the URL that the frontend should use to serve the file.
 */
export const generateFileURL = ({ filename }: { filename: string }): string =>
  `${process.env.NEXT_PUBLIC_FRONTEND_URL!}/media/${filename}`
